### ISSUE TITLE
Implement patch database

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#10]
The patch library is currently pulling data from a GSS:
https://docs.google.com/spreadsheets/d/1ocSb1dTeOm8YgeqDOAGsfLddZrGxzAbymuq0bz5ZQ3Q/edit#gid=0

The spreadsheet should be replaced with a relational database.

The Author field should be connected to the user database.

Several audio (soundcloud) and video samples could potentially be associated with each patch.

**Comment by samuele-artuso** [comment]
Update:
* I added the script I was mentioning (71a5e96cba8050b1facfe73dcd4edcb3b4baa5d2) to this repository.
* The script can now pull data directly from the Google Spreadsheet.

**Comment by samuele-artuso** [comment]
The staging and production APIs are both up and running on bella, respectively on port 3000 and 3001.

I configured Apache to run as a reverse proxy on both bella and buenaventura so as to expose the APIs under `/api`. While this worked without problems for the staging environment (test: http://staging.hoxtonowl.com/api/patches/findAll), it didn't for the production API — it will just time out and I think the reason is that bella's port 3001 is behind a firewall.

On a side note, I had to upgrade MongoDB from the very outdated 1.4 version to 2.6. The upgrade seem to have worked a treat, but please check it didn't break other services that are using mongo. There's a full DB dump in my home directory on bella should you need it.

**Comment by samuele-artuso** [comment]
The staging website is now pulling data from Mongo, through the REST API.

[This script](https://github.com/pingdynasty/OwlServer/blob/master/utils/owl-patch-db-import/app.js) that reads the patch data from the GSS and puts it into Mongo. I think we could cronjob it (maybe hourly) — this means that you could keep on using the GSS as though nothing had changed. If we go for this solution, it's worth pointing out that every time the script is run, Mongo will assign a totally new id to each patch. This is probably not a problem now, but it's something to bear in mind for the future.

**Comment by GuillaumeLeNost** [comment]
Very cool !!!


Guillaume

**Comment by samuele-artuso** [comment]
This is complete, but not live (waiting for new server). Leaving it open until then.
