### ISSUE TITLE
Remove patch link (Soundcloud / Github) not working

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlServer#61]
The first item in the list of links (same for Soundcloud and github) can't be removed.
If there is more than one link in the list, the remove button on the first item will remove the second item.
Chrome / Linux / live server (nestor)

**Comment by pingdynasty** [comment]
to clarify: this is when editing patch details

**Comment by samuele-artuso** [comment]
I can't reproduce this bug.

If there's more than one link in the list, the remove button on the first item will remove the *first* item, not the second one. Checked on Firefox and Chrome, on Linux.

It is true that the first item cannot be removed, and this is intentional even if the workflow may not seem clear. You can actually remove the first link by clearing the text field. This will effectively remove all the SC/GH links in the database.

If you think it's worth it, I can make the first "remove" link clear the text field next to it, but I may have to hack the "repeated field" component I'm using.

Let me know what you think.

**Comment by samuele-artuso** [comment]
can I close this?

**Comment by pingdynasty** [comment]
done
